syncs:
  - repos:
      - Sogeti-Service-Center/terraform-aws-feature-cps-itsmintegration
      # - Sogeti-Service-Center/terraform-aws-feature-cps-itsmintegration
      # - Sogeti-Service-Center/terraform-aws-feature-cps-networkandconnectivity
      # - Sogeti-Service-Center/terraform-aws-feature-psw-backupservice
      # - Sogeti-Service-Center/terraform-aws-spoke-kubernetes
      # - Sogeti-Service-Center/terraform-aws-feature-cps-base
      # - Sogeti-Service-Center/terraform-aws-buildingblocks
      # - Sogeti-Service-Center/terraform-aws-feature-psw-iamrotation
      # - Sogeti-Service-Center/terraform-aws-feature-psw-scheduling
      # - Sogeti-Service-Center/terraform-aws-feature-customerfoundation-vulnerabilityscanning
      # - Sogeti-Service-Center/terraform-aws-feature-cps-platformsecurityservice
      # - Sogeti-Service-Center/terraform-aws-feature-cps-platformmonitoring
      # - Sogeti-Service-Center/terraform-aws-feature-cps-accessmanagement
      # - Sogeti-Service-Center/terraform-aws-feature-cps-controlsandguardrails
      # - Sogeti-Service-Center/terraform-aws-feature-cps-platformlifecyclemanagement
      # - Sogeti-Service-Center/terraform-aws-feature-psw-updatemanagement
      # - Sogeti-Service-Center/terraform-aws-feature-ces-database
      # - Sogeti-Service-Center/terraform-aws-feature-psw-monitoringasaservice
      # - Sogeti-Service-Center/terraform-aws-feature-psw-workloadlogging
      # - Sogeti-Service-Center/terraform-aws-feature-psw-configurationmanagement
      # - Sogeti-Service-Center/terraform-aws-feature-psw-endpointprotection
    files:
      - src: workflows/auto-merge-syncs.yaml
        dest: .github/workflows/auto-merge-syncs.yaml