syncs:
  - repos:
      - deltaprojects/hello-kubernetes
      - deltaprojects/intranet
      - deltaprojects/delta-dashkiosk-k8s
      - deltaprojects/bisnode-upload-k8s
      - deltaprojects/kafka-manager-k8s
      - deltaprojects/github-actions-dashboard
      - deltaprojects/lightair-k8s
    files:
      - src: workflows/build-and-deploy.yaml
        dest: .github/workflows/build-and-deploy.yaml
