
on: pull_request

jobs:
  merge:
    name: "Auto merge workflow syncs"

    runs-on: "ubuntu-latest"

    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false && (
        github.event.action == 'opened' ||
        github.event.action == 'reopened' ||
        github.event.action == 'synchronize'
      ) && (
        github.actor == 'gh-file-sync[bot]'
      )

    steps:
      - name: Merge pull request for ${{ github.event.client_payload.ReleaseBranchName }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.pulls.merge({
              merge_method: "rebase",
              owner: context.repo.owner,
              pull_number: context.payload.pull_request.number,
              repo: context.repo.repo,
            })
