on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
    - 'docs/**'
    - '**/README.md'
    - '**/LICENSE'
    - '**/.gitignore'

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      # Using buildx (https://docs.docker.com/buildx/working-with-buildx/).
      # You can use a custom_build in your Tiltfile to utilize buildx.
      # Something like this:
      # custom_build(
      #   'ghcr.io/ORGNAME/REPO',
      #   'docker buildx build -t $EXPECTED_REF -t ORGNAME/REPO:latest -f Dockerfile --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new --push ./',
      #   ['.'],
      #   skips_local_docker=True,
      #   disable_push=True,
      # )
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        driver: docker-container
        driver-opts: |
          image=moby/buildkit:rootless
          network=host

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Docker Hub
      # Create a access token in docker hub -> settings -> security.
      # Create two GitHub secrets DOCKER_HUB_USERNAME and DOCKER_HUB_ACCESS_TOKEN.
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Install kube tools
      uses: yokawasa/action-setup-kube-tools@v0.4.0

    # commenting out, context actions are severely limited.
    # - name: auth with k8s, build, push & deploy with tilt
    #   uses: deltaprojects/action-tilt-auth-bpd@master
    #   with:
    #     rancher-context: ${{ secrets.RANCHER_CONTEXT }}
    #     rancher-token: ${{ secrets.RANCHER_TOKEN }}
    #     rancher-url: ${{ secrets.RANCHER_URL }}

    # - name: configure kubectl from secret
    #   shell: bash
    #   run: |
    #     if ! [[ -z "${{ secrets.KUBE_CONFIG }}" ]]; then
    #       mkdir -p ${HOME}/.kube/ && echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ${HOME}/.kube/config
    #     fi

    - name: configure kubectl from Rancher API key
      shell: bash
      run: |
        if ! [[ -z "${{ secrets.RANCHER_CONTEXT }}" || -z "${{ secrets.RANCHER_CONTEXT }}" || -z "${{ secrets.RANCHER_URL }}" ]]; then
          rancher login --skip-verify --context ${{ secrets.RANCHER_CONTEXT }} --token ${{ secrets.RANCHER_TOKEN }} ${{ secrets.RANCHER_URL }}
          mkdir -p ${HOME}/.kube
          rancher kubectl config view --minify --raw > ${HOME}/.kube/config
          KUBE_CLUSTER_URL=$(kubectl config view --minify -o 'jsonpath={.clusters[0].cluster.server}')
          KUBE_CONTEXT=$(kubectl config view --minify -o 'jsonpath={.current-context}')
          kubectl config set-cluster ${KUBE_CONTEXT} --insecure-skip-tls-verify=true --server=${KUBE_CLUSTER_URL}
        else
          echo needs secrets RANCHER_CONTEXT, RANCHER_CONTEXT and RANCHER_URL
          exit 1
        fi

    - name: Build, push and deploy
      shell: bash
      run: |
        docker buildx use --default --global ${{ steps.buildx.outputs.name }}
        tilt ci

    - name: Move cache (work-around)
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
