on: push

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      # Using buildx (https://docs.docker.com/buildx/working-with-buildx/).
      # You can use a custom_build in your Tiltfile to utilize buildx.
      # Something like this:
      # custom_build(
      #   'ghcr.io/ORGNAME/REPO',
      #   'docker buildx build -t $EXPECTED_REF -f Dockerfile --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache --push ./',
      #   ['./'],
      #   skips_local_docker=True,
      #   disable_push=True,
      # )
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        driver: docker-container
        driver-opts: |
          image=moby/buildkit:rootless
          network=host

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Docker Hub
      # Create a access token in docker hub -> settings -> security.
      # Create two GitHub secrets DOCKER_HUB_USERNAME and DOCKER_HUB_ACCESS_TOKEN.
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Install kube tools
      uses: yokawasa/action-setup-kube-tools@v0.4.0

    - name: auth with k8s, build, push & deploy with tilt
      uses: deltaprojects/action-tilt-auth-bpd@master
      with:
        rancher-context: ${{ secrets.RANCHER_CONTEXT }}
        rancher-token: ${{ secrets.RANCHER_TOKEN }}
        rancher-url: ${{ secrets.RANCHER_URL }}
