name: Security Check
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.tflint.hcl'
  pull_request:
  workflow_dispatch:


jobs:
  build-matrix:
    name: Determine modules
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - id: set-matrix
        run: echo "::set-output name=modules::$(find . -maxdepth 2 -mindepth 2 -type f -name 'main.tf' | sed -r 's|/[^/]+$||' |sort |uniq |jq -c --slurp --raw-input 'split("\n") | [.[] | select(. != "")]')"
    outputs:
      modules: ${{ steps.set-matrix.outputs.modules }}

  validate-code:
    needs: build-matrix
    name: Validate
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.build-matrix.outputs.modules) }}
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Decrypt secrets
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: |
          openssl aes-256-cbc -in .github/workflows/secrets/id_rsa.enc -out .github/workflows/secrets/id_rsa -pass pass:$ENCRYPTION_KEY -d -pbkdf2
 
      - name: Setup SSH agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          chmod 0600 .github/workflows/secrets/id_rsa
          ssh-add .github/workflows/secrets/id_rsa
        
      - name: Checkout sogeti github tools
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: git clone git@github.com:Sogeti-Service-Center/github-tools.git
      
      - name: Install Terraform and tfsec
        run: |
          chmod +x github-tools/tools/*
          sudo mv github-tools/tools/* /usr/local/bin/
          mv github-tools/tfsecvalidation/ ./.tfsec/
          terraform --version
          tfsec --version

      - name: Initiate tfsec
        run: |
          echo Entering validator phase..
          # remove below mentioned echo, to run the validation
          tfsec --concise-output --no-color

      - name: Cleanup
        if: always()
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-add -D
          rm -Rf *