name: Simple Code Validator
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.tflint.hcl'
  pull_request:
  workflow_dispatch:

jobs:
  build-matrix:
    name: Determine modules
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - id: set-matrix
        run: echo "::set-output name=modules::$(find . -maxdepth 2 -mindepth 2 -type f -name 'main.tf' | sed -r 's|/[^/]+$||' |sort |uniq |jq -c --slurp --raw-input 'split("\n") | [.[] | select(. != "")]')"
        
    outputs:
      modules: ${{ steps.set-matrix.outputs.modules }}

  validate-code:
    needs: build-matrix
    name: Validate
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.build-matrix.outputs.modules) }}
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install prerequisites
        run: sudo apt-get install unzip

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1
      
      - name: Init Terraform
        run: terraform init
        working-directory: ${{ matrix.module }}
      
      - name: Validate Terraform
        run: terraform validate
        working-directory: ${{ matrix.module }}

      - name: Install tflint
        run: |
            sudo curl -s https://raw.githubusercontent.com/terraform-linters/tflint/v0.34.1/install_linux.sh | bash
            echo tflint api_version
            tflint --version
        working-directory: ${{ matrix.module }}

      - name: Initialize tflint
        run: tflint --init
        working-directory: ${{ matrix.module }}

      - name: Execute tflint
        run: tflint
        working-directory: ${{ matrix.module }}