on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    # git tag v1.0.2
    # git push origin --tags
    tags:
    - "v*"
    paths-ignore:
    - 'docs/**'
    - '**/README.md'
    - '**/LICENSE'
    - '**/.gitignore'

jobs:
  tilt:
    name: Setup and Execute Tilt
    runs-on: ubuntu-latest
    steps:
      # This should be moved to the composite action when this issue is closed https://github.com/actions/runner/issues/834
      - name: set RELEASE_TAG variable.
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        # This does the same:
        # if: github.event_name == 'push' && github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v')
        # github.ref == 'refs/tags/v1.2.5' or 'refs/heads/feature-branch-1'
        # github.event.ref == 'v1.2.5' or 'feature-branch-1'
        shell: bash
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # If not public
      # - uses: actions/checkout@v2
      #   with:
      #     repository: deltaprojects/action-tilt-ci-cd
      #     path: tilt-action
      #     token: XXX
      # - uses: ./tilt-action/workflows/tilt
      # if public
      - uses: deltaprojects/action-tilt-ci-cd/workflows/tilt@master
        with:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RANCHER_CONTEXT: ${{ secrets.RANCHER_CONTEXT }}
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
