on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    # git tag v1.0.2
    # git push origin --tags
    tags:
    - "v*"
    paths-ignore:
    - 'docs/**'
    - '**/README.md'
    - '**/LICENSE'
    - '**/.gitignore'

jobs:
  tilt:
    name: Initialize and Execute Tilt
    runs-on: ubuntu-latest
    steps:
      # If not public
      # - uses: actions/checkout@v2
      #   with:
      #     repository: deltaprojects/action-ci-cd
      #     path: auth-action
      #     token: XXX
      # - uses: ./auth-action/workflows/auth
      # if public
      - uses: deltaprojects/action-tilt-ci-cd/workflows/auth@master
        with:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RANCHER_CONTEXT: ${{ secrets.RANCHER_CONTEXT }}
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}

      - name: Execute Tilt
        shell: bash
        run: tilt ci
